### ISSUE TITLE
Fix imperfection in the internationalization build

### ISSUE THREAD

**Issue by AlexisL61** [AlexisL61/JackboxUtility#11]
## TODO

- [x] Server duplication when choosing a server
- [x] Hide title when they are not used 
- [x] Multiline for pack description 
- [x] Remove description of a pack in the packs.json file
- [x] Add variables NATIVELY_TRANSLATED and COMMUNITY_TRANSLATED  
- [x] Change the main image and text by the server main image and text (and do it in the patch page too)
- [x] Add indication on the app icon about the download progress 
- [x] Add website info in info.json
- [x] Credits too long in the patch info
- [x] Alert when closing the app and the app is downloading
