### ISSUE TITLE
All patch tab

### ISSUE THREAD

**Issue by AlexisL61** [AlexisL61/JackboxUtility#13]
## Description

Add an “All patches” tab to see every patches available and download them easily.

## Todo

- [x] Create the tab
- [x] Add the packs in it by categories
- [x] Download everything at once
