### ISSUE TITLE
Settings tweaks

### ISSUE THREAD

**Issue by AkiraArtuhaxis** [AlexisL61/JackboxUtility#38]
The settings could use some tweaks, although they're minor ones:

- Gear icon next to the Settings title
- Icons next to each game
- Move the change of language server there

The big change would be to add little “Restore” buttons, which would prompt you to restore the game back to its original state (using the verify files option from either Steam or EGS). I don't know if EGS restore can be done with commands tho.
![SettingsMockup](https://user-images.githubusercontent.com/93792993/233869832-a0155bdc-f45f-457a-a188-99b819c34b2c.png)

## TODO

- [x] Gear icon
- [x] Game images
- [x] Redo parameters with server info and app info
- [x] Should not be able to select the same game
- [x] Hide the add games button when all games have been added 
- [x] Translate the “Authors” and “Contributors” strings
- [x] Bugs to fix
   - [x] Not the good game visible when trying to add a game after deleting a game

**Comment by AkiraArtuhaxis** [comment]
Things missing:
- A "Restore" button which would prompt you to verify the games with Steam in order to restore them back to English (see list of commands necessary here: https://discord.com/channels/@me/1085647431598870559/1101270561314832494). It's currently unknown if this set of commands exist for Epic Games Store. In which game, it'd be a Steam exclusive feature, and the button should only appear if your version is from Steam.
- When adding a game, if you already added that game, it shouldn't appear in the dropdown list (meaning that the only selectable games should be the ones not added yet).
