### ISSUE TITLE
Manage languages

### ISSUE THREAD

**Issue by AlexisL61** [AlexisL61/JackboxUtility#4]
# Description

As the project goes international, a user should be able to select a language to download patches only for the selected language.
Every language should have their own infrastructure to distribute patches (their own packs.json, welcome.json and assets).
As a language will not be implemented regularly, every link to a language server will be written in the app directly (not in a main server).
Since the app is open source, a user should also add a custom server (e.g. for testing, or just to create is own patch server)

# Links

- Flutter tutoriel for internationalization : https://docs.flutter.dev/development/accessibility-and-localization/internationalization
- Library used : https://api.flutter.dev/flutter/flutter_localizations/flutter_localizations-library.html

# TODO

- [x] Preparation
   - [x] Create a app_en.arb (and a app_fr.arb) containing every string used by the app
   - [x] Translate app_en.arb to a language and generate the app_<language>.arb
   - [x] Add the .arb file to the app
- [x] Development
   - [x] Choose a language page
      - [x] Visible in parameters
      - [x] Visible when the app is launched the first time
      - [x] Add the custom server page
