### ISSUE TITLE
Download pack

### ISSUE THREAD

**Issue by AlexisL61** [AlexisL61/JackboxUtility#5]
# Description

A user should be able to download a pack (and not each game at a time).

As every language doesn't use the “download a pack” function (french for example), we should have these three available interfaces (sketch, not final) : 

![Image](https://user-images.githubusercontent.com/30233189/225712837-2ab10580-975f-4950-980b-4e37f67789bb.png)

# TODO

- [ ] Development
    - [ ] Design
       - [x] Second interface done
       - [x] Third interface done
       - [ ] Add a page where you can download every pack at once
    - [x] Download a pack
       - [x] Download a pack patch function
       - [x] Saving the downloaded patch version
