### ISSUE TITLE
Automatic game detection

### ISSUE THREAD

**Issue by AlexisL61** [AlexisL61/JackboxUtility#6]
# Description

The app should be able to detect installed games on startup and by clicking on a button.

On Windows, we can find installed games in registry.
- Steam : 
The registry location `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Valve\Steam` show the installed path.
We can open the `<Path>/steamapps/libraryfolders.vdf` file to get the installed games in a json format (with appId etc).

- Epic Games : 
The registry location `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Epic Games\EpicGamesLauncher` show the AppData path.
We can open the `<Path>/../../UnrealEngineLauncher\LauncherInstalled.dat` to get the installed games and the path.

# Links

More info : 
- https://github.com/NPBruce/valkyrie/issues/1056
- https://stackoverflow.com/questions/58388230/how-to-read-the-steam-install-path-from-the-windows-registry
- Read the win32 registry on flutter : https://pub.dev/packages/win32_registry
- Reading Steam and Epic games games file : https://github.com/DasDarki/JBPPP2/blob/master/JBPPP2/Controllers/LauncherController.cs

# TODO

- [x] Development
   - [x] Read the registry file
   - [x] Update the path with the registry
   - [x] Run the automatic path update on first startup
   - [x] Run the automatic path update without confirmation
